/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTB0 (number 43), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_NORTE_VERDE_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NORTE_VERDE_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NORTE_VERDE_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NORTE_VERDE_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                              /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_NORTE_AMARILLO_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NORTE_AMARILLO_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NORTE_AMARILLO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NORTE_AMARILLO_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                                 /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_NORTE_ROJO_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NORTE_ROJO_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NORTE_ROJO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NORTE_ROJO_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                             /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */
#define BOARD_INITPINS_NORTE_VUELTA_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NORTE_VUELTA_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NORTE_VUELTA_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NORTE_VUELTA_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                               /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_NORTE_SENSOR_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_NORTE_SENSOR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_NORTE_SENSOR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_NORTE_SENSOR_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                               /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_SUR_VERDE_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SUR_VERDE_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SUR_VERDE_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SUR_VERDE_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                            /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_SUR_AMARILLO_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SUR_AMARILLO_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SUR_AMARILLO_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SUR_AMARILLO_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                               /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_SUR_ROJO_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SUR_ROJO_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SUR_ROJO_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SUR_ROJO_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                           /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_SUR_VUELTA_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SUR_VUELTA_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SUR_VUELTA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SUR_VUELTA_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                             /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_SUR_SENSOR_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SUR_SENSOR_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SUR_SENSOR_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SUR_SENSOR_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                             /* @} */

/*! @name PORTC5 (number 62), J1[9]
  @{ */
#define BOARD_INITPINS_ESTE_VERDE_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_ESTE_VERDE_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_ESTE_VERDE_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ESTE_VERDE_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                             /* @} */

/*! @name PORTC4 (number 61), J1[7]
  @{ */
#define BOARD_INITPINS_ESTE_AMARILLO_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_ESTE_AMARILLO_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_ESTE_AMARILLO_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ESTE_AMARILLO_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                                /* @} */

/*! @name PORTC3 (number 58), J1[5]
  @{ */
#define BOARD_INITPINS_ESTE_ROJO_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_ESTE_ROJO_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_ESTE_ROJO_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ESTE_ROJO_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                            /* @} */

/*! @name PORTC0 (number 55), J1[3]
  @{ */
#define BOARD_INITPINS_ESTE_VUELTA_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_ESTE_VUELTA_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_ESTE_VUELTA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ESTE_VUELTA_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                              /* @} */

/*! @name PORTC7 (number 64), J1[1]
  @{ */
#define BOARD_INITPINS_ESTE_SENSOR_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_ESTE_SENSOR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_ESTE_SENSOR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ESTE_SENSOR_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                              /* @} */

/*! @name PORTA4 (number 30), J1[10]/D4
  @{ */
#define BOARD_INITPINS_OESTE_VERDE_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OESTE_VERDE_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OESTE_VERDE_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OESTE_VERDE_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                              /* @} */

/*! @name PORTA12 (number 32), J1[8]/D3
  @{ */
#define BOARD_INITPINS_OESTE_AMARILLO_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OESTE_AMARILLO_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OESTE_AMARILLO_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OESTE_AMARILLO_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                                 /* @} */

/*! @name PORTD4 (number 77), J1[6]/D2
  @{ */
#define BOARD_INITPINS_OESTE_ROJO_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_OESTE_ROJO_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_OESTE_ROJO_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_OESTE_ROJO_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                             /* @} */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_OESTE_VUELTA_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OESTE_VUELTA_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OESTE_VUELTA_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OESTE_VUELTA_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                               /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_OESTE_SENSOR_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OESTE_SENSOR_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OESTE_SENSOR_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OESTE_SENSOR_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
